language: node_js
services:
  - docker
install:
  - docker-compose -f docker-compose.test.yml build
script:
  - docker-compose -f docker-compose.test.yml up
after_script:
  - docker-compose -f docker-compose.test.yml down
